### ISSUE TITLE
Debug images output

### ISSUE THREAD

**Issue by fire** [RechieKho/iree.gd#10]
Rechie helped out with machine learning image upscaling working on vulkan. 

## Input

![](https://cdn.discordapp.com/attachments/1096880534531100672/1101171063292969011/anime_girl_input.jpg)

## Output

![](https://cdn.discordapp.com/attachments/1096880534531100672/1101171063502671994/anime_girl_output.jpg)

## Setup

1.  Use the precompiled ESRGAN model from GitHub https://tfhub.dev/captain-pool/lite-model/esrgan-tf2/1
2. Check that you got the tflite model
3.  Convert from tflite to vmfb
```
python3 -m pip install \
  iree-compiler \
  iree-runtime \
  iree-tools-tflite
iree-import-tflite lite-model_esrgan-tf2_1.tflite -o lite-model_esrgan-tf2_1.iree
iree-compile     --iree-input-type=tosa     --iree-hal-target-backends=vulkan     lite-model_esrgan-tf2_1.iree     -o esrgan-tf2_1-iree.vmfb --iree-vm-bytecode-module-optimize --iree-vm-bytecode-module-output-format=flatbuffer-binary
```
4.  Call the model using the following code:
    
```gdscript
extends Node2D

func _ready():
	var compressed_image : Texture2D = load("res://anime_input.jpeg")
	var input_image : Image = compressed_image.get_image()
	if not input_image:
		return
	var iree_module: IREEModule = IREEModule.new()
	var error = iree_module.load("res://esrgan-tf2_1-iree.vmfb")
	if error != OK:
		return
	var result: Array = iree_module.call_vmfb(String("module.main"), IREEBufferView.from([input_image], IREEBufferView.FLOAT_32) )
	for buffer in result:
		var output := buffer.to_images(Image.FORMAT_RGBF) as Array 
		for image in output:         
			print(image)
			image.save_png("res://scaled_anime_output.png")
```
    
6.  Remember to convert and resize the image using `image.convert(Image.FORMAT_RGBF)` and `image.resize(50, 50)`.
7.  Note that RGBF is not the same as RGB8. Images are typically 8 bits per channel and not 4 floats.
8.  Consider using the `to_images` method instead of `to_image`.
9.  The model takes 3 float channels as input and outputs 3 float channels.
10.  Refer to TensorFlow Lite's Super Resolution example for more information: [https://www.tensorflow.org/lite/examples/super\_resolution/overview](https://www.tensorflow.org/lite/examples/super_resolution/overview)

**Comment by RechieKho** [comment]
Update: So basically esrgan output f32 in 0-255 range while godot 4's float format is between 0-1.

This sounds concerning because it looks like I need to restructure the IREEBufferView's method so it has some basic manipulation API (cast, clamp & etc). IREE itself only provide low-level function so someone need to burn the time to write those buffer view api.

**Comment by RechieKho** [comment]
Update: esrgan prefer input's color range in 0-255. The green channel will diminish if the input color range given is in 0-1 range.

**Comment by RechieKho** [comment]
It is better to use iree-compile from iree-dist instead of from python's pip.

**Comment by RechieKho** [comment]
Using color range in 0-255 instead of Godot's 0-1 range.

# Anime girl
![anime_input](https://github.com/RechieKho/iree.gd/assets/50512341/4d632a27-8728-4b9a-aad6-ad13bf608f33)
![esrganed](https://github.com/RechieKho/iree.gd/assets/50512341/35d2def9-f346-4091-8fb4-669d9d073132)

# Baboon
![baboon_esrgan](https://github.com/RechieKho/iree.gd/assets/50512341/bcfec165-4d7d-4e8f-aa60-b496830bc612)
![massive_baboon_esrgan](https://github.com/RechieKho/iree.gd/assets/50512341/91cfa5e1-f49b-4bdd-9f4b-f1e52753e0c0)

# Shrek
![shrek](https://github.com/RechieKho/iree.gd/assets/50512341/5242603b-e731-42d9-ae58-68846c863bce)
![esrganed-shrek](https://github.com/RechieKho/iree.gd/assets/50512341/b2b9c294-8fbc-48e5-9a15-1ab273e70324)

# Code
There is a major API change...
```
extends Node2D

func _ready():
	var compressed_image : Texture2D = load("res://shrek.jpeg")
	var input_image : Image = compressed_image.get_image()
	var raw_input_data := input_image.get_data()
	var clean_input_data := PackedFloat32Array()
	for i in raw_input_data: clean_input_data.append(i)
	var dimension := [1, 50, 50, 3]
	
	var input_tensor := IREETensor.new()
	input_tensor.capture_float32s(clean_input_data, dimension)
	
	var iree_module: IREEModule = IREEModule.new()
	var error = iree_module.load("res://bytecodes/esrgan/esrgan-tf2_1-iree.vmfb")
	if error != OK:
		return
	var tensors: Array = iree_module.call_vmfb("module.main", [input_tensor])
	for e in tensors:
		var tensor := e as IREETensor
		var raw_data := tensor.get_data()
		var clean_data := PackedByteArray()
		for f in raw_data.to_float32_array(): clean_data.append(clamp(f, 0, 255))
		Image.create_from_data(200, 200, false, Image.FORMAT_RGB8, clean_data).save_jpg("res://esrganed-shrek.jpeg")
```

**Comment by RechieKho** [comment]
For the blurriness, it is likely that I didn't do a better when cleaning data.

People using esrgan would probably need to take a look at how they do it in [collab](https://www.tensorflow.org/hub/tutorials/image_enhancing)
