### ISSUE TITLE
Godot godot-cpp @ 6f127fc does not exist

### ISSUE THREAD

**Issue by fire** [RechieKho/iree.gd#14]
[godot-cpp @ 6f127fc](https://github.com/godotengine/godot-cpp/tree/6f127fc0bc7c6bc632dae12809c4898e6514e292)

**Comment by RechieKho** [comment]
Oops, that commit is from my own fork of godot-cpp, I revert it back.
In order to compile iree.gd, you'll need to compile godot with [this PR](https://github.com/godotengine/godot/pull/80322) (aka [this branch](https://github.com/RechieKho/gobread/tree/export-vulkan-instance-proc-addr-fn)), and then generate `extension_api.json` in `godot-cpp` (that commit is basically commit updated version of `extension_api.json`) 

Currently it is kind of awkward to deal with, and I don't have a solution to solve this temporary awkwardness, everything will be OK after PR is accepted and godot-cpp is updated. But it would be nice to deal with this.

**Comment by fire** [comment]
Can you hard code a extension_api.json somewhere and point godot-cpp to it?

**Comment by RechieKho** [comment]
Like put my version of extension_api.json into a temporary directory in this repo?

**Comment by fire** [comment]
Yup

**Comment by RechieKho** [comment]
Here you go: https://github.com/RechieKho/iree.gd/tree/tmp-extension-api

**Comment by RechieKho** [comment]
Change of tide, we are going to load the vulkan function ourselves, so there is no need for api changes. See #11
