### ISSUE TITLE
Recreate the test on Windows

### ISSUE THREAD

**Issue by fire** [RechieKho/iree.gd#19]
Rechui shared a link to a branch that preserves the old Vulkan backend implementation. Rechui advised Fire to remove a specific line in the CMakeLists.txt file which sets the host binary directory.

```diff
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/tools)
```

This line was supposed to be removed after repurposing the tools directory from storing host binaries to scripts for easy compilation of tflite models.

iFire asked if the old way has the buffer vector design, to which Rechui responded affirmatively. The current implementation accepts PackedByteArray and allows defining your own dimension, making it low level enough to accept most formats, unless Godot cannot read it.

### Relevant Links:

1. [Godot Pull Request](https://github.com/godotengine/godot/pull/80322)
2. [Branch preserving old Vulkan backend](https://github.com/RechieKho/iree.gd/tree/tmp-extension-api)
3. [Line to remove in CMakeLists.txt](https://github.com/RechieKho/iree.gd/blob/tmp-extension-api/CMakeLists.txt#L47C1-L47C61)

**Comment by RechieKho** [comment]
Never know that I could fix this vulkan loader issue, use the new vulkan backend instead :100:

**Comment by RechieKho** [comment]
Action for compiling for windows is completed. But do take note of this: https://github.com/RechieKho/iree.gd/pull/25#issuecomment-1716882521

**Comment by RechieKho** [comment]
I have successfully run `iree.gd` on x86_64 windows. 
[sample.zip](https://github.com/RechieKho/iree.gd/files/12602781/sample.zip)

Here is what need to take note of:
- Use Godot 4.2 instead of 4.1
- `iree-gd.gdextension`'s path is incorrect
- Rename library to `iree-gd.windows.debug.dll` instead of `release` as it uses `debug` library for running in editor.

@fire You can try this out. If this work, then you can close this issue.

**Comment by fire** [comment]
I tested with https://github.com/godotengine/godot-builds/releases/tag/4.2-dev4. It launches then crashes.

**Comment by fire** [comment]
This bug is a bit confusing I'll recreate.
