### ISSUE TITLE
Improve demo ease of use

### ISSUE THREAD

**Issue by fire** [RechieKho/iree.gd#61]
### Issue description

Reduce the number of steps to enable the demo.

1. had to set res://scenes/main/main.tscn to be loaded on start
1. UI/TextureRect `load_path` is set to `res://bytecodes/esrgan/esrgan.vulkan.vmfb` on Windows

### Steps to reproduce

1. Download
2. Launch with Godot Engine steam
3. Hit play and demo doesn't run

### Minimal reproduction project (For SDK or engine issues)

https://github.com/RechieKho/iree.gd/releases/download/v0.0.1-alpha3/iree-gd-sample-v0.0.1-alpha3.zip

### Using a released version?

Yes

### What OS? Any other relevant information? (iree.gd revision, System information)

Windows, Nvidia, RTX 3090

**Comment by RechieKho** [comment]
For the first step, we could just set `main.tscn` as the main scene.
For the second step, It is hard. It will work on windows and linux, but not for the rest of the platform.

**Comment by fire** [comment]
I am ok with windows and linux working first

**Comment by fire** [comment]
I think that we need to export each platform as a separate export variable and then use os detection to switch between

**Comment by RechieKho** [comment]
Yea, I just realised that Godot have this `OS.get_name()` which can be used to know the platform. But in order to implement this switch. I might need to defer context initialisation as currently it will just shout at you immediately as you load the `.vmfb` (initialising context of an incompatible byte code). So I need to deal with that by deferring the "error-yelling" to `IREEModule.run_module` before this.
